
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectodsl;

import java_cup.runtime.Symbol;
import java.util.HashSet;
import java_cup.runtime.XMLElement;

/** CUP v0.11b 20160615 (GIT 4ac7450) generated parser.
  */
@SuppressWarnings({"rawtypes"})
public class AnalisisSintactico extends java_cup.runtime.lr_parser {

 public final Class getSymbolContainer() {
    return Simbolo.class;
}

  /** Default constructor. */
  @Deprecated
  public AnalisisSintactico() {super();}

  /** Constructor which sets the default scanner. */
  @Deprecated
  public AnalisisSintactico(java_cup.runtime.Scanner s) {super(s);}

  /** Constructor which sets the default scanner. */
  public AnalisisSintactico(java_cup.runtime.Scanner s, java_cup.runtime.SymbolFactory sf) {super(s,sf);}

  /** Production table. */
  protected static final short _production_table[][] = 
    unpackFromStrings(new String[] {
    "\000\040\000\002\002\004\000\002\002\007\000\002\003" +
    "\004\000\002\003\003\000\002\004\003\000\002\004\003" +
    "\000\002\004\004\000\002\011\002\000\002\005\010\000" +
    "\002\012\002\000\002\005\010\000\002\013\002\000\002" +
    "\005\010\000\002\014\002\000\002\005\010\000\002\015" +
    "\002\000\002\005\010\000\002\016\002\000\002\005\010" +
    "\000\002\017\002\000\002\005\010\000\002\020\002\000" +
    "\002\005\010\000\002\021\002\000\002\005\010\000\002" +
    "\022\002\000\002\005\010\000\002\006\004\000\002\006" +
    "\003\000\002\007\005\000\002\007\007\000\002\010\013" +
    "" });

  /** Access to production table. */
  public short[][] production_table() {return _production_table;}

  /** Parse-action table. */
  protected static final short[][] _action_table = 
    unpackFromStrings(new String[] {
    "\000\133\000\004\004\004\001\002\000\004\030\007\001" +
    "\002\000\004\002\006\001\002\000\004\002\001\001\002" +
    "\000\004\023\010\001\002\000\032\003\021\005\025\006" +
    "\027\007\022\010\026\011\015\012\014\013\013\014\011" +
    "\015\012\016\024\022\016\001\002\000\004\030\131\001" +
    "\002\000\004\030\124\001\002\000\004\030\117\001\002" +
    "\000\004\030\112\001\002\000\004\030\105\001\002\000" +
    "\004\030\075\001\002\000\034\003\ufffe\005\ufffe\006\ufffe" +
    "\007\ufffe\010\ufffe\011\ufffe\012\ufffe\013\ufffe\014\ufffe\015" +
    "\ufffe\016\ufffe\022\ufffe\024\ufffe\001\002\000\034\003\ufffc" +
    "\005\ufffc\006\ufffc\007\ufffc\010\ufffc\011\ufffc\012\ufffc\013" +
    "\ufffc\014\ufffc\015\ufffc\016\ufffc\022\ufffc\024\ufffc\001\002" +
    "\000\004\025\074\001\002\000\004\030\067\001\002\000" +
    "\034\003\ufffd\005\ufffd\006\ufffd\007\ufffd\010\ufffd\011\ufffd" +
    "\012\ufffd\013\ufffd\014\ufffd\015\ufffd\016\ufffd\022\ufffd\024" +
    "\ufffd\001\002\000\004\030\062\001\002\000\004\030\055" +
    "\001\002\000\004\030\050\001\002\000\004\030\033\001" +
    "\002\000\034\003\021\005\025\006\027\007\022\010\026" +
    "\011\015\012\014\013\013\014\011\015\012\016\024\022" +
    "\016\024\032\001\002\000\034\003\uffff\005\uffff\006\uffff" +
    "\007\uffff\010\uffff\011\uffff\012\uffff\013\uffff\014\uffff\015" +
    "\uffff\016\uffff\022\uffff\024\uffff\001\002\000\004\002\000" +
    "\001\002\000\004\023\034\001\002\000\004\017\ufff8\001" +
    "\002\000\004\017\037\001\002\000\006\017\037\024\046" +
    "\001\002\000\004\032\041\001\002\000\006\017\uffe5\024" +
    "\uffe5\001\002\000\006\020\043\025\042\001\002\000\006" +
    "\017\uffe4\024\uffe4\001\002\000\004\031\044\001\002\000" +
    "\004\025\045\001\002\000\006\017\uffe3\024\uffe3\001\002" +
    "\000\034\003\ufff7\005\ufff7\006\ufff7\007\ufff7\010\ufff7\011" +
    "\ufff7\012\ufff7\013\ufff7\014\ufff7\015\ufff7\016\ufff7\022\ufff7" +
    "\024\ufff7\001\002\000\006\017\uffe6\024\uffe6\001\002\000" +
    "\004\023\051\001\002\000\004\017\ufff4\001\002\000\004" +
    "\017\037\001\002\000\006\017\037\024\054\001\002\000" +
    "\034\003\ufff3\005\ufff3\006\ufff3\007\ufff3\010\ufff3\011\ufff3" +
    "\012\ufff3\013\ufff3\014\ufff3\015\ufff3\016\ufff3\022\ufff3\024" +
    "\ufff3\001\002\000\004\023\056\001\002\000\004\017\ufffa" +
    "\001\002\000\004\017\037\001\002\000\006\017\037\024" +
    "\061\001\002\000\034\003\ufff9\005\ufff9\006\ufff9\007\ufff9" +
    "\010\ufff9\011\ufff9\012\ufff9\013\ufff9\014\ufff9\015\ufff9\016" +
    "\ufff9\022\ufff9\024\ufff9\001\002\000\004\023\063\001\002" +
    "\000\004\017\uffe8\001\002\000\004\017\037\001\002\000" +
    "\006\017\037\024\066\001\002\000\034\003\uffe7\005\uffe7" +
    "\006\uffe7\007\uffe7\010\uffe7\011\uffe7\012\uffe7\013\uffe7\014" +
    "\uffe7\015\uffe7\016\uffe7\022\uffe7\024\uffe7\001\002\000\004" +
    "\023\070\001\002\000\004\017\ufff6\001\002\000\004\017" +
    "\037\001\002\000\006\017\037\024\073\001\002\000\034" +
    "\003\ufff5\005\ufff5\006\ufff5\007\ufff5\010\ufff5\011\ufff5\012" +
    "\ufff5\013\ufff5\014\ufff5\015\ufff5\016\ufff5\022\ufff5\024\ufff5" +
    "\001\002\000\034\003\ufffb\005\ufffb\006\ufffb\007\ufffb\010" +
    "\ufffb\011\ufffb\012\ufffb\013\ufffb\014\ufffb\015\ufffb\016\ufffb" +
    "\022\ufffb\024\ufffb\001\002\000\004\026\076\001\002\000" +
    "\004\032\077\001\002\000\004\027\100\001\002\000\004" +
    "\030\101\001\002\000\004\026\102\001\002\000\004\032" +
    "\103\001\002\000\004\025\104\001\002\000\034\003\uffe2" +
    "\005\uffe2\006\uffe2\007\uffe2\010\uffe2\011\uffe2\012\uffe2\013" +
    "\uffe2\014\uffe2\015\uffe2\016\uffe2\022\uffe2\024\uffe2\001\002" +
    "\000\004\023\106\001\002\000\004\017\ufff2\001\002\000" +
    "\004\017\037\001\002\000\006\017\037\024\111\001\002" +
    "\000\034\003\ufff1\005\ufff1\006\ufff1\007\ufff1\010\ufff1\011" +
    "\ufff1\012\ufff1\013\ufff1\014\ufff1\015\ufff1\016\ufff1\022\ufff1" +
    "\024\ufff1\001\002\000\004\023\113\001\002\000\004\017" +
    "\ufff0\001\002\000\004\017\037\001\002\000\006\017\037" +
    "\024\116\001\002\000\034\003\uffef\005\uffef\006\uffef\007" +
    "\uffef\010\uffef\011\uffef\012\uffef\013\uffef\014\uffef\015\uffef" +
    "\016\uffef\022\uffef\024\uffef\001\002\000\004\023\120\001" +
    "\002\000\004\017\uffee\001\002\000\004\017\037\001\002" +
    "\000\006\017\037\024\123\001\002\000\034\003\uffed\005" +
    "\uffed\006\uffed\007\uffed\010\uffed\011\uffed\012\uffed\013\uffed" +
    "\014\uffed\015\uffed\016\uffed\022\uffed\024\uffed\001\002\000" +
    "\004\023\125\001\002\000\004\017\uffea\001\002\000\004" +
    "\017\037\001\002\000\006\017\037\024\130\001\002\000" +
    "\034\003\uffe9\005\uffe9\006\uffe9\007\uffe9\010\uffe9\011\uffe9" +
    "\012\uffe9\013\uffe9\014\uffe9\015\uffe9\016\uffe9\022\uffe9\024" +
    "\uffe9\001\002\000\004\023\132\001\002\000\004\017\uffec" +
    "\001\002\000\004\017\037\001\002\000\006\017\037\024" +
    "\135\001\002\000\034\003\uffeb\005\uffeb\006\uffeb\007\uffeb" +
    "\010\uffeb\011\uffeb\012\uffeb\013\uffeb\014\uffeb\015\uffeb\016" +
    "\uffeb\022\uffeb\024\uffeb\001\002" });

  /** Access to parse-action table. */
  public short[][] action_table() {return _action_table;}

  /** <code>reduce_goto</code> table. */
  protected static final short[][] _reduce_table = 
    unpackFromStrings(new String[] {
    "\000\133\000\004\002\004\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\012" +
    "\003\027\004\016\005\022\010\017\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\010\004\030\005\022\010\017" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\012\034\001\001\000\006\006\035\007\037" +
    "\001\001\000\004\007\046\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\014\051" +
    "\001\001\000\006\006\052\007\037\001\001\000\004\007" +
    "\046\001\001\000\002\001\001\000\002\001\001\000\004" +
    "\011\056\001\001\000\006\006\057\007\037\001\001\000" +
    "\004\007\046\001\001\000\002\001\001\000\002\001\001" +
    "\000\004\022\063\001\001\000\006\006\064\007\037\001" +
    "\001\000\004\007\046\001\001\000\002\001\001\000\002" +
    "\001\001\000\004\013\070\001\001\000\006\006\071\007" +
    "\037\001\001\000\004\007\046\001\001\000\002\001\001" +
    "\000\002\001\001\000\002\001\001\000\002\001\001\000" +
    "\002\001\001\000\002\001\001\000\002\001\001\000\002" +
    "\001\001\000\002\001\001\000\002\001\001\000\002\001" +
    "\001\000\004\015\106\001\001\000\006\006\107\007\037" +
    "\001\001\000\004\007\046\001\001\000\002\001\001\000" +
    "\002\001\001\000\004\016\113\001\001\000\006\006\114" +
    "\007\037\001\001\000\004\007\046\001\001\000\002\001" +
    "\001\000\002\001\001\000\004\017\120\001\001\000\006" +
    "\006\121\007\037\001\001\000\004\007\046\001\001\000" +
    "\002\001\001\000\002\001\001\000\004\021\125\001\001" +
    "\000\006\006\126\007\037\001\001\000\004\007\046\001" +
    "\001\000\002\001\001\000\002\001\001\000\004\020\132" +
    "\001\001\000\006\006\133\007\037\001\001\000\004\007" +
    "\046\001\001\000\002\001\001" });

  /** Access to <code>reduce_goto</code> table. */
  public short[][] reduce_table() {return _reduce_table;}

  /** Instance of action encapsulation class. */
  protected CUP$AnalisisSintactico$actions action_obj;

  /** Action encapsulation object initializer. */
  protected void init_actions()
    {
      action_obj = new CUP$AnalisisSintactico$actions(this);
    }

  /** Invoke a user supplied parse action. */
  public java_cup.runtime.Symbol do_action(
    int                        act_num,
    java_cup.runtime.lr_parser parser,
    java.util.Stack            stack,
    int                        top)
    throws java.lang.Exception
  {
    /* call code in generated class */
    return action_obj.CUP$AnalisisSintactico$do_action(act_num, parser, stack, top);
  }

  /** Indicates start state. */
  public int start_state() {return 0;}
  /** Indicates start production. */
  public int start_production() {return 0;}

  /** <code>EOF</code> Symbol index. */
  public int EOF_sym() {return 0;}

  /** <code>error</code> Symbol index. */
  public int error_sym() {return 1;}



    public HashSet<String> dispositivos = new HashSet<>();
    public HashSet<String> interfacesUsadas = new HashSet<>();

    public java.util.HashMap<String, HashSet<String>> interfacesPorDispositivo = new java.util.HashMap<>();
    public java.util.HashMap<String, String> tipoDispositivo = new java.util.HashMap<>();
    public java.util.HashMap<String, java.util.HashMap<String, String>> ipPorInterfaz = new java.util.HashMap<>();

    public String uml = "@startuml\n";
    public String dispositivoActual = null;
    public String errores = "";

    public String obtenerUML() {
        return uml + "@enduml";
    }

    public void generarNodos() {
    String nodos = "";

    for(String d : dispositivos) {
        String tipo = tipoDispositivo.get(d);
        String texto = "";

        HashSet<String> interfaces = interfacesPorDispositivo.get(d);
        java.util.HashMap<String, String> mapaIps = ipPorInterfaz.get(d);

        if(interfaces != null) {
            for(String i : interfaces) {
                if(mapaIps != null && mapaIps.containsKey(i)) {
                    texto += i + ": " + mapaIps.get(i) + "\\n";
                } else {
                    texto += i + "\\n";
                }
            }
        }

        switch(tipo) {
            case "router":
                nodos += "database \"Router " + d + "\\n" + texto + "\" as " + d + "\n";
                break;

            case "firewall":
                nodos += "rectangle \"Firewall " + d + "\\n" + texto + "\" as " + d + "\n";
                break;

            case "switch":
                nodos += "component \"Switch " + d + "\\n" + texto + "\" as " + d + "\n";
                break;

            case "switchL3":
                nodos += "component \"Switch L3 " + d + "\\n" + texto + "\" as " + d + "\n";
                break;

            case "server":
                nodos += "rectangle \"Server " + d + "\\n" + texto + "\" as " + d + "\n";
                break;

            case "pc":
                nodos += "note \"" + d + "\\n" + texto + "\" as " + d + "\n";
                break;

            case "laptop":
                nodos += "note \"Laptop " + d + "\\n" + texto + "\" as " + d + "\n";
                break;

            case "mobile":
                nodos += "note \"Mobile " + d + "\\n" + texto + "\" as " + d + "\n";
                break;

            case "accesspoint":
                nodos += "node \"" + d + "\\nAccess Point\\n" + texto + "\" as " + d + "\n";
                break;

            case "internet":
                nodos += "cloud \"Internet " + d + "\\n" + texto + "\" as " + d + "\n";
                break;
        }
    }

    uml = "@startuml\n" +
          "title Red generada automáticamente\n\n" +
          nodos +
          uml.substring("@startuml\n".length());
    }   

    @Override
    public void syntax_error(Symbol s){
        errores += "Error sintáctico en token: " + s.value +
                   " | línea: " + s.left +
                   " | columna: " + s.right + "\n";
    }

    @Override
    public void unrecovered_syntax_error(Symbol s){
        errores += "Error fatal de sintaxis en token: " + s.value +
                   " | línea: " + s.left +
                   " | columna: " + s.right + "\n";
    }


/** Cup generated class to encapsulate user supplied action code.*/
@SuppressWarnings({"rawtypes", "unchecked", "unused"})
class CUP$AnalisisSintactico$actions {
  private final AnalisisSintactico parser;

  /** Constructor */
  CUP$AnalisisSintactico$actions(AnalisisSintactico parser) {
    this.parser = parser;
  }

  /** Method 0 with the actual generated action code for actions 0 to 300. */
  public final java_cup.runtime.Symbol CUP$AnalisisSintactico$do_action_part00000000(
    int                        CUP$AnalisisSintactico$act_num,
    java_cup.runtime.lr_parser CUP$AnalisisSintactico$parser,
    java.util.Stack            CUP$AnalisisSintactico$stack,
    int                        CUP$AnalisisSintactico$top)
    throws java.lang.Exception
    {
      /* Symbol object for return from actions */
      java_cup.runtime.Symbol CUP$AnalisisSintactico$result;

      /* select the action based on the action number */
      switch (CUP$AnalisisSintactico$act_num)
        {
          /*. . . . . . . . . . . . . . . . . . . .*/
          case 0: // $START ::= inicio EOF 
            {
              Object RESULT =null;
		int start_valleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int start_valright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		Object start_val = (Object)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;
		RESULT = start_val;
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("$START",0, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          /* ACCEPT */
          CUP$AnalisisSintactico$parser.done_parsing();
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 1: // inicio ::= RED ID LLAVE_ABIERTA lista_instrucciones LLAVE_CERRADA 
            {
              Object RESULT =null;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("inicio",0, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 2: // lista_instrucciones ::= lista_instrucciones instruccion 
            {
              Object RESULT =null;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 3: // lista_instrucciones ::= instruccion 
            {
              Object RESULT =null;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("lista_instrucciones",1, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 4: // instruccion ::= dispositivo 
            {
              Object RESULT =null;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 5: // instruccion ::= conexion 
            {
              Object RESULT =null;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 6: // instruccion ::= error PUNTO_COMA 
            {
              Object RESULT =null;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("instruccion",2, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 7: // NT$0 ::= 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;

          dispositivoActual = nombre;
          if(dispositivos.contains(nombre)) {
              errores += "Error: dispositivo duplicado: " + nombre + "\n";
          } else {
              dispositivos.add(nombre);
              interfacesPorDispositivo.put(nombre, new HashSet<>());
              tipoDispositivo.put(nombre, "router");
              ipPorInterfaz.put(nombre, new java.util.HashMap<>());
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("NT$0",7, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 8: // dispositivo ::= ROUTER ID LLAVE_ABIERTA NT$0 lista_interfaces LLAVE_CERRADA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$0
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-2)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).value;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("dispositivo",3, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 9: // NT$1 ::= 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;

          dispositivoActual = nombre;
          if(dispositivos.contains(nombre)) {
              errores += "Error: dispositivo duplicado: " + nombre + "\n";
          } else {
              dispositivos.add(nombre);
              interfacesPorDispositivo.put(nombre, new HashSet<>());
              tipoDispositivo.put(nombre, "firewall");
              ipPorInterfaz.put(nombre, new java.util.HashMap<>());
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("NT$1",8, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 10: // dispositivo ::= FIREWALL ID LLAVE_ABIERTA NT$1 lista_interfaces LLAVE_CERRADA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$1
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-2)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).value;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("dispositivo",3, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 11: // NT$2 ::= 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;

          dispositivoActual = nombre;
          if(dispositivos.contains(nombre)) {
              errores += "Error: dispositivo duplicado: " + nombre + "\n";
          } else {
              dispositivos.add(nombre);
              interfacesPorDispositivo.put(nombre, new HashSet<>());
              tipoDispositivo.put(nombre, "switch");
              ipPorInterfaz.put(nombre, new java.util.HashMap<>());
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("NT$2",9, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 12: // dispositivo ::= SWITCH ID LLAVE_ABIERTA NT$2 lista_interfaces LLAVE_CERRADA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$2
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-2)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).value;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("dispositivo",3, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 13: // NT$3 ::= 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;

          dispositivoActual = nombre;
          if(dispositivos.contains(nombre)) {
              errores += "Error: dispositivo duplicado: " + nombre + "\n";
          } else {
              dispositivos.add(nombre);
              interfacesPorDispositivo.put(nombre, new HashSet<>());
              tipoDispositivo.put(nombre, "switchL3");
              ipPorInterfaz.put(nombre, new java.util.HashMap<>());
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("NT$3",10, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 14: // dispositivo ::= SWITCHL3 ID LLAVE_ABIERTA NT$3 lista_interfaces LLAVE_CERRADA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$3
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-2)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).value;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("dispositivo",3, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 15: // NT$4 ::= 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;

          dispositivoActual = nombre;
          if(dispositivos.contains(nombre)) {
              errores += "Error: dispositivo duplicado: " + nombre + "\n";
          } else {
              dispositivos.add(nombre);
              interfacesPorDispositivo.put(nombre, new HashSet<>());
              tipoDispositivo.put(nombre, "server");
              ipPorInterfaz.put(nombre, new java.util.HashMap<>());
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("NT$4",11, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 16: // dispositivo ::= SERVER ID LLAVE_ABIERTA NT$4 lista_interfaces LLAVE_CERRADA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$4
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-2)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).value;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("dispositivo",3, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 17: // NT$5 ::= 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;

          dispositivoActual = nombre;
          if(dispositivos.contains(nombre)) {
              errores += "Error: dispositivo duplicado: " + nombre + "\n";
          } else {
              dispositivos.add(nombre);
              interfacesPorDispositivo.put(nombre, new HashSet<>());
              tipoDispositivo.put(nombre, "pc");
              ipPorInterfaz.put(nombre, new java.util.HashMap<>());
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("NT$5",12, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 18: // dispositivo ::= PC ID LLAVE_ABIERTA NT$5 lista_interfaces LLAVE_CERRADA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$5
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-2)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).value;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("dispositivo",3, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 19: // NT$6 ::= 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;

          dispositivoActual = nombre;
          if(dispositivos.contains(nombre)) {
              errores += "Error: dispositivo duplicado: " + nombre + "\n";
          } else {
              dispositivos.add(nombre);
              interfacesPorDispositivo.put(nombre, new HashSet<>());
              tipoDispositivo.put(nombre, "laptop");
              ipPorInterfaz.put(nombre, new java.util.HashMap<>());
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("NT$6",13, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 20: // dispositivo ::= LAPTOP ID LLAVE_ABIERTA NT$6 lista_interfaces LLAVE_CERRADA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$6
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-2)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).value;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("dispositivo",3, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 21: // NT$7 ::= 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;

          dispositivoActual = nombre;
          if(dispositivos.contains(nombre)) {
              errores += "Error: dispositivo duplicado: " + nombre + "\n";
          } else {
              dispositivos.add(nombre);
              interfacesPorDispositivo.put(nombre, new HashSet<>());
              tipoDispositivo.put(nombre, "mobile");
              ipPorInterfaz.put(nombre, new java.util.HashMap<>());
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("NT$7",14, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 22: // dispositivo ::= MOBILE ID LLAVE_ABIERTA NT$7 lista_interfaces LLAVE_CERRADA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$7
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-2)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).value;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("dispositivo",3, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 23: // NT$8 ::= 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;

          dispositivoActual = nombre;
          if(dispositivos.contains(nombre)) {
              errores += "Error: dispositivo duplicado: " + nombre + "\n";
          } else {
              dispositivos.add(nombre);
              interfacesPorDispositivo.put(nombre, new HashSet<>());
              tipoDispositivo.put(nombre, "accesspoint");
              ipPorInterfaz.put(nombre, new java.util.HashMap<>());
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("NT$8",15, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 24: // dispositivo ::= ACCESSPOINT ID LLAVE_ABIERTA NT$8 lista_interfaces LLAVE_CERRADA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$8
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-2)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).value;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("dispositivo",3, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 25: // NT$9 ::= 
            {
              Object RESULT =null;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;

          dispositivoActual = nombre;
          if(dispositivos.contains(nombre)) {
              errores += "Error: dispositivo duplicado: " + nombre + "\n";
          } else {
              dispositivos.add(nombre);
              interfacesPorDispositivo.put(nombre, new HashSet<>());
              tipoDispositivo.put(nombre, "internet");
              ipPorInterfaz.put(nombre, new java.util.HashMap<>());
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("NT$9",16, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 26: // dispositivo ::= INTERNET ID LLAVE_ABIERTA NT$9 lista_interfaces LLAVE_CERRADA 
            {
              Object RESULT =null;
              // propagate RESULT from NT$9
                RESULT = (Object) ((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-2)).value;
		int nombreleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).left;
		int nombreright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).right;
		String nombre = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)).value;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("dispositivo",3, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 27: // lista_interfaces ::= lista_interfaces interfaz 
            {
              Object RESULT =null;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("lista_interfaces",4, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 28: // lista_interfaces ::= interfaz 
            {
              Object RESULT =null;

              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("lista_interfaces",4, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 29: // interfaz ::= INTERFAZ NOMBRE_INTERFAZ PUNTO_COMA 
            {
              Object RESULT =null;
		int nombreIfleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int nombreIfright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String nombreIf = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;
		
          if(dispositivoActual != null) {
              HashSet<String> lista = interfacesPorDispositivo.get(dispositivoActual);
              if(lista != null) {
                  if(lista.contains(nombreIf)) {
                      errores += "Error: interfaz duplicada en " + dispositivoActual + ": " + nombreIf + "\n";
                  } else {
                      lista.add(nombreIf);
                  }
              }
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("interfaz",5, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-2)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 30: // interfaz ::= INTERFAZ NOMBRE_INTERFAZ IP DIRECCION_IP PUNTO_COMA 
            {
              Object RESULT =null;
		int nombreIfleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-3)).left;
		int nombreIfright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-3)).right;
		String nombreIf = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-3)).value;
		int dirleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int dirright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String dir = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;
		
          if(dispositivoActual != null) {
              HashSet<String> lista = interfacesPorDispositivo.get(dispositivoActual);
              if(lista != null) {
                  if(lista.contains(nombreIf)) {
                      errores += "Error: interfaz duplicada en " + dispositivoActual + ": " + nombreIf + "\n";
                  } else {
                      lista.add(nombreIf);
                      ipPorInterfaz.get(dispositivoActual).put(nombreIf, dir);
                  }
              }
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("interfaz",5, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-4)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /*. . . . . . . . . . . . . . . . . . . .*/
          case 31: // conexion ::= CONECTAR ID PUNTO NOMBRE_INTERFAZ FLECHA ID PUNTO NOMBRE_INTERFAZ PUNTO_COMA 
            {
              Object RESULT =null;
		int origenleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-7)).left;
		int origenright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-7)).right;
		String origen = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-7)).value;
		int ifOrigenleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)).left;
		int ifOrigenright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)).right;
		String ifOrigen = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-5)).value;
		int destinoleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-3)).left;
		int destinoright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-3)).right;
		String destino = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-3)).value;
		int ifDestinoleft = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).left;
		int ifDestinoright = ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).right;
		String ifDestino = (String)((java_cup.runtime.Symbol) CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-1)).value;
		
          boolean origenValido = true;
          boolean destinoValido = true;

          if(!dispositivos.contains(origen)) {
              errores += "Error: dispositivo no existe: " + origen + "\n";
              origenValido = false;
          }

          if(!dispositivos.contains(destino)) {
              errores += "Error: dispositivo no existe: " + destino + "\n";
              destinoValido = false;
          }

          if(origenValido) {
              HashSet<String> listaOrigen = interfacesPorDispositivo.get(origen);
              if(listaOrigen != null && !listaOrigen.contains(ifOrigen)) {
                  errores += "Error: interfaz no existe en " + origen + ": " + ifOrigen + "\n";
                  origenValido = false;
              }
          }

          if(destinoValido) {
              HashSet<String> listaDestino = interfacesPorDispositivo.get(destino);
              if(listaDestino != null && !listaDestino.contains(ifDestino)) {
                  errores += "Error: interfaz no existe en " + destino + ": " + ifDestino + "\n";
                  destinoValido = false;
              }
          }

          if(origenValido) {
              String usoOrigen = origen + "." + ifOrigen;
              if(interfacesUsadas.contains(usoOrigen)) {
                  errores += "Error: interfaz ya usada: " + usoOrigen + "\n";
                  origenValido = false;
              } else {
                  interfacesUsadas.add(usoOrigen);
              }
          }

          if(destinoValido) {
              String usoDestino = destino + "." + ifDestino;
              if(interfacesUsadas.contains(usoDestino)) {
                  errores += "Error: interfaz ya usada: " + usoDestino + "\n";
                  destinoValido = false;
              } else {
                  interfacesUsadas.add(usoDestino);
              }
          }

          if(origenValido && destinoValido) {
              uml += origen + " -- " + destino + " : " + ifOrigen + " ↔ " + ifDestino + "\n";
          }
      
              CUP$AnalisisSintactico$result = parser.getSymbolFactory().newSymbol("conexion",6, ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.elementAt(CUP$AnalisisSintactico$top-8)), ((java_cup.runtime.Symbol)CUP$AnalisisSintactico$stack.peek()), RESULT);
            }
          return CUP$AnalisisSintactico$result;

          /* . . . . . .*/
          default:
            throw new Exception(
               "Invalid action number "+CUP$AnalisisSintactico$act_num+"found in internal parse table");

        }
    } /* end of method */

  /** Method splitting the generated action code into several parts. */
  public final java_cup.runtime.Symbol CUP$AnalisisSintactico$do_action(
    int                        CUP$AnalisisSintactico$act_num,
    java_cup.runtime.lr_parser CUP$AnalisisSintactico$parser,
    java.util.Stack            CUP$AnalisisSintactico$stack,
    int                        CUP$AnalisisSintactico$top)
    throws java.lang.Exception
    {
              return CUP$AnalisisSintactico$do_action_part00000000(
                               CUP$AnalisisSintactico$act_num,
                               CUP$AnalisisSintactico$parser,
                               CUP$AnalisisSintactico$stack,
                               CUP$AnalisisSintactico$top);
    }
}

}
