
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615
//----------------------------------------------------

package proyectodsl;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int CONCAT = 19;
  public static final int IMPRIMIR = 36;
  public static final int ENTERO = 45;
  public static final int SI = 39;
  public static final int DIFERENTE = 35;
  public static final int CASE = 13;
  public static final int DOS_PUNTOS = 18;
  public static final int ENTONCES = 40;
  public static final int ASTERISCO = 38;
  public static final int PARENTESIS_ABIERTO = 2;
  public static final int FOR = 10;
  public static final int LLAVE_ABIERTA = 16;
  public static final int NOT = 23;
  public static final int AND = 22;
  public static final int IGUAL = 27;
  public static final int OR = 21;
  public static final int IF = 6;
  public static final int ID = 47;
  public static final int PUNTO_COMA = 4;
  public static final int IGUAL_IGUAL = 24;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int COMA = 5;
  public static final int CADENA = 46;
  public static final int MODULO = 32;
  public static final int MENOS = 29;
  public static final int MENOR = 25;
  public static final int BREAK = 15;
  public static final int SWITCH = 12;
  public static final int MAYOR = 26;
  public static final int POTENCIA = 31;
  public static final int NO = 41;
  public static final int PUTS = 20;
  public static final int ELSE = 7;
  public static final int WHILE = 9;
  public static final int DEFAULT = 14;
  public static final int MAYOR_IGUAL = 33;
  public static final int FALSO = 43;
  public static final int END = 8;
  public static final int CONCATENACION = 37;
  public static final int PARENTESIS_CERRADO = 3;
  public static final int VERDADERO = 44;
  public static final int LLAVE_CERRADA = 17;
  public static final int MENOR_IGUAL = 34;
  public static final int FINSI = 42;
  public static final int DIVISION = 30;
  public static final int DO = 11;
  public static final int MAS = 28;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PARENTESIS_ABIERTO",
  "PARENTESIS_CERRADO",
  "PUNTO_COMA",
  "COMA",
  "IF",
  "ELSE",
  "END",
  "WHILE",
  "FOR",
  "DO",
  "SWITCH",
  "CASE",
  "DEFAULT",
  "BREAK",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "DOS_PUNTOS",
  "CONCAT",
  "PUTS",
  "OR",
  "AND",
  "NOT",
  "IGUAL_IGUAL",
  "MENOR",
  "MAYOR",
  "IGUAL",
  "MAS",
  "MENOS",
  "DIVISION",
  "POTENCIA",
  "MODULO",
  "MAYOR_IGUAL",
  "MENOR_IGUAL",
  "DIFERENTE",
  "IMPRIMIR",
  "CONCATENACION",
  "ASTERISCO",
  "SI",
  "ENTONCES",
  "NO",
  "FINSI",
  "FALSO",
  "VERDADERO",
  "ENTERO",
  "CADENA",
  "ID"
  };
}

