
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package proyectodsl;

/** CUP generated class containing symbol constants. */
public class Simbolo {
  /* terminals */
  public static final int SWITCHL3 = 6;
  public static final int PUNTO = 20;
  public static final int CADENA = 25;
  public static final int NOMBRE_INTERFAZ = 24;
  public static final int SERVER = 7;
  public static final int IP = 14;
  public static final int CONECTAR = 16;
  public static final int INTERNET = 12;
  public static final int FLECHA = 21;
  public static final int SWITCH = 5;
  public static final int INTERFAZ = 13;
  public static final int ID = 22;
  public static final int FIREWALL = 4;
  public static final int RED = 2;
  public static final int DIRECCION_IP = 23;
  public static final int TIPO = 15;
  public static final int LLAVE_ABIERTA = 17;
  public static final int ROUTER = 3;
  public static final int EOF = 0;
  public static final int MOBILE = 10;
  public static final int error = 1;
  public static final int PUNTO_COMA = 19;
  public static final int PC = 8;
  public static final int LAPTOP = 9;
  public static final int LLAVE_CERRADA = 18;
  public static final int ACCESSPOINT = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "RED",
  "ROUTER",
  "FIREWALL",
  "SWITCH",
  "SWITCHL3",
  "SERVER",
  "PC",
  "LAPTOP",
  "MOBILE",
  "ACCESSPOINT",
  "INTERNET",
  "INTERFAZ",
  "IP",
  "TIPO",
  "CONECTAR",
  "LLAVE_ABIERTA",
  "LLAVE_CERRADA",
  "PUNTO_COMA",
  "PUNTO",
  "FLECHA",
  "ID",
  "DIRECCION_IP",
  "NOMBRE_INTERFAZ",
  "CADENA"
  };
}

